# Github Action for laravel.
# Setup using mysql and redis.
name: WebTheory Test Action

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  webtheory-unit-tests:
    name: Unit Test with PHP 7.4, MySQL and Redis

    # use latest ubuntu machine
    runs-on: ubuntu-latest

    # setup environment variables globally
    env:
      DB_CONNECTION: mysql
      DB_DATABASE: appdb
      DB_USERNAME: root
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      #CACHE_DRIVER: redis
      #QUEUE_CONNECTION: redis
      #SESSION_DRIVER: redis

    # install MySQL and Redis.
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: appdb
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # perform following steps to install application and configure it.
    steps:

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, dom, fileinfo, mysql
          # coverage: xdebug

      - name: Install Application
        uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Configure application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate --force --no-interaction --verbose
          php artisan migrate --force --no-interaction --verbose
          php artisan db:seed --class=UsersTableSeeder --force --no-interaction --verbose
          php artisan db:seed --class=IncrementalSeeder --force --no-interaction --verbose
          php artisan storage:link --no-interaction --verbose
          php artisan config:clear --no-interaction --verbose
          cp -rf storage/repo/templates/Serenity/* resources/views/active/
          cp -rf storage/repo/templates/Serenity resources/views/templates/
          php artisan cache:clear --no-interaction --verbose
          php artisan config:clear --no-interaction --verbose
          php artisan route:clear --no-interaction --verbose
          php artisan view:clear --no-interaction --verbose
          php artisan event:clear --no-interaction --verbose
          php artisan config:cache --no-interaction --verbose
          php artisan route:cache --no-interaction --verbose
          chmod -R 777 storage bootstrap/cache
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: appdb
          APP_ENV: production
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        run: vendor/bin/phpunit
